# -*- coding: utf-8 -*-
"""Exemplo functions.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pZPmfpCZPv_bX2T2B44xHCzYDx59LvSx
"""

!pip install pyspark

from pyspark.sql import SparkSession
from pyspark.sql import functions as f

spark = SparkSession.builder.appName("SparkStreaming").getOrCreate()

tweets=[
    ["Estou muito animado com esse projeto! Esse sim vai m... https://t.co/u4EGCRvwPb"],
    ["@danpsiqueira @Rodrigo A área de engenharia de dados só vai crescer"],
    ["RT @Rodrigotechlead: Eu estou preparando uma formação inédita para todos que queiram começar na área"],
    ["RT @Davidneves: O meu objetivo é converter o maior número de bolas de 3 no jogo"],
    ["RT @RomuloSM: https://t.co/yuoLpFEboa"],
    ["@Renato @David Sucesso total que fala..."],
    ["RT @MariaDB: Meus gatos são muito lindos, e eu posso provar"],
    ["RT @beatriz2801: Não vejo a hora de produzir o curso de Dax avançado...."],
    ["@Afonso Vou fazer um dashboard do @Flamengo  💪❤️🖤\n#CRF #VamosFlamengo https://t.co/6Uhokyh6YL"],
    ["RT @Libertadores: 🙌 ¡Los equipos ya clasificados a los octavos de final de la CONMEBOL #Libertadores!\n🇦🇷 @EdelpOficial y @CATalleresdecba…"],
    ["RT @MillenaG: @Igor Deixa eu te falar então...\nSim. Os engenheiros do açaí vem com tudo"],
]

tweets = spark.createDataFrame(tweets, ['tweets'])

tweets.show(truncate=False)

type(tweets)

tweets\
    .select(f.split('tweets', " ").alias('word'))\
    .show(truncate=False)

tweets\
    .select(f.explode(f.split('tweets', " ")).alias('word'))\
    .show(50, truncate=False)

tweets\
    .select(f.explode(f.split('tweets', " ")).alias('word'))\
    .withColumn('word', f.regexp_replace('word', r'http\S+', ''))\
    .withColumn('word', f.regexp_replace('word', '@\w+', ''))\
    .withColumn('word', f.regexp_replace('word', '#', ''))\
    .withColumn('word', f.regexp_replace('word', 'RT', ''))\
    .withColumn('word', f.regexp_replace('word', ':', ''))\
    .na.replace('', None)\
    .na.drop()\
    .show(50, truncate=False)